apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: frappe
  name: frappe
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frappe
    spec:
      containers:
      - image: frappe
        name: frappe
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 6787
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench
          name: frappe-claim0
        - mountPath: /home/frappe/frappe-bench/config/redis-cache.conf
          name: frappe-claim1
        - mountPath: /home/frappe/frappe-bench/config/redis-queue.conf
          name: frappe-claim2
        - mountPath: /home/frappe/frappe-bench/config/redis-socketio.conf
          name: frappe-claim3
      restartPolicy: Always
      volumes:
      - name: frappe-claim0
        persistentVolumeClaim:
          claimName: frappe-claim0
      - name: frappe-claim1
        persistentVolumeClaim:
          claimName: frappe-claim1
      - name: frappe-claim2
        persistentVolumeClaim:
          claimName: frappe-claim2
      - name: frappe-claim3
        persistentVolumeClaim:
          claimName: frappe-claim3
status: {}
