apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: frappe
  name: frappe
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "6787"
    port: 6787
    targetPort: 6787
  selector:
    io.kompose.service: frappe
status:
  loadBalancer: {}
