apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-queue
  name: redis-queue
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-queue
    spec:
      containers:
      - args:
        - redis-server
        - /etc/conf.d/redis_queue.conf
        image: redis:alpine
        name: redis-queue
        resources: {}
        volumeMounts:
        - mountPath: /etc/conf.d
          name: redis-queue-claim0
      restartPolicy: Always
      volumes:
      - name: redis-queue-claim0
        persistentVolumeClaim:
          claimName: redis-queue-claim0
status: {}
